branch-defaults:
  master:
    environment: LaravelQaApp-env
global:
  application_name: Laravel-QA-App
  default_ec2_keyname: XXXXXX
  default_platform: 64bit Amazon Linux 2018.03 v2.8.7 running PHP 7.2
  default_region: eu-west-2
  sc: git
